# Generated by Django 4.1.7 on 2023-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_rename_application_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, upload_to='advertisement/img/%Y/%m/%d'),
        ),
    ]
